### PR TITLE
adding secrets management

### PR DESCRIPTION
**Pull request by xuminx**
adding secrets management
moving snowflake decrypting steps to ff_classes

### CODE REVIEW

**Comment by xuminx** [comment]
grant_permission usage: image
currently iterate through each table in finance_accounting and grant permission, will intergrate the method to specific table.

**Review by lawrence-chin — COMMENTED** [review]
This is approved, but I need to update the version and upload a new package. Any changes need to be updated via versions or else it will cause issues. Is there any other changes needed @xuminx ?

**Comment by xuminx** [comment]
@lawrence-chin this is ready now; This PR including both secret management class AND find_logger_v2 method.

**Comment by xuminx** [comment]
@lawrence-chin this is ready now; This PR including both secret management class AND find_logger_v2 method.

**Pull request merged**
